/** @type {import('tailwindcss').Config} */
const { fontFamily } = require('tailwindcss/defaultTheme');

const plugin = require('tailwindcss/plugin');

module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    mode: 'jit',
    // These paths are just examples, customize them to match your project structure
    purge: ['./public/**/*.html', './src/**/*.{js,jsx,ts,tsx,vue}'],
    extend: {
      aspectRatio: {
        '111/49': '120/49',
        '222/49': '240/49',
      },
      lineHeight: {
        '83px': '83px',
      },
      fontFamily: {
        // display: ['var(--font-roc)', ...fontFamily.sans],
        display: ['var(--font-body)', ...fontFamily.sans],
        body: ['var(--font-body)', ...fontFamily.sans],
        sans: ['var(--font-body)', ...fontFamily.sans],
      },

      colors: {
        'ab-purple-light': '#7C7295',
        'ab-purple-dark': '#414379',
        'ab-purple-dark-v1': '#1F1C5A',
        'ab-purple-dark-v2': '#18164F',
        'ab-green-dark': '#313f24',
        'ab-pink-light': '#FFA5EB',
        'ab-blue-light': '#5B8DFF',
        'ab-blue-light-v2': '#83FFFF',
        'ab-green-light': '#C2FA49',
        'ab-yellow-light': '#FCFF68',
        'ab-red-light': '#FFA18C',
        'ab-orange': '#9A8CDB',
        // 'ab-orange': '#F24A25',
        'ab-orange-light': '#DED2F5',
        // 'ab-orange-light': '#edd1c1',
        // 'ab-orange-light': '#edd1c1',
        'ab-orange-dark': 'rgba(237, 209, 193, 0.3)',
        'ab-white': '#F5F5F5',
        'ab-white-v1': '#F9F6FF',
        'ab-dark-white': 'rgba(255, 255, 255, 0.16)',
        'ab-light-white': 'rgba(255, 255, 255, 0.9)',
        'ab-gray-1': '#D9D9D9',
        'ab-gray-v2': '#DED2F566',

        'ab-gray-v3': '#F1ECFB',
        'ab-gray-v4': '#DED2F5BF',
        'ab-gray-v5': '#CAC0DA',
        'ab-gray-v6': '#DED2F580',
        'ab-gray-v7': '#DED2F55E',
        'ab-gray-v8': '#DED2F526',
        'ab-blue-dark': '#101628',
        'ab-black-v1': '#0D0D25',
        'ab-black-v2': '#010119',
        'ab-black-v3': '#111827',
        'ab-black-v5': '#020218',
        'ab-black-v6': '#0E092A',
        'ab-black-v7': '#130118',
        'ab-black-v8': '#0E032D',
        'ab-black-v9': '#04072f',
        'ab-black-v10': '#0F0431',
        'ab-black-v11': '#0A0738',
        'ab-black-v12': '#060A19',
        'ab-black-v13': '#060327',
        'ab-black-v14': '#140D41',
        'ab-black-v15': '#020020',
        'ab-black-v16': '#151559',
        'ab-violet': '#6A6EB1',
        'ab-violet-transparent': 'rgba(106, 110, 177, 0.1)',
        'ab-violet-dark': '#6531D2',
        'ab-violet-secondary': '#5218F7',
        'ab-violet-v1': '#362B7C',
        'ab-violet-v2': '#58599C',
        'ab-violet-v3': '#1D0E4A',
        'ab-violet-v4': '#2C1F60',
        'ab-violet-v5': '#26155C',
        'ab-violet-v6': '#362E65',
        'ab-light-gray': '#DFDFDF',
        'ab-light-gray-v1': '#FBF7F1',
        'ab-light-gray-v2': '#FBF8F3',
        'ab-gray': '#54607E',
        'ab-gray-v1': '#ABACB9',
        'ab-shadow-gray': '#FFFFFF1A',
        'ab-dark': 'rgba(255, 255, 255, 0.05)',
        'ab-dark-v2': 'rgba(255, 255, 255, 0.16)',
        'ab-dark-v3': 'rgba(255, 255, 255, 0.36)',
        'ab-dark-v4': 'rgba(255, 255, 255, 0.9)',
        'ab-dark-v5': '#36344E',
        'ab-black': '#101628',
        'ab-warm-gray': '#C9C6C2',
        'ab-black-v4': '#11182780',
        'ab-yellow': '#F3D8C4',
        'ab-white-transparent': '#9CA3AF1A',
        'ab-gray-transparent': '#54607E80',
        'ab-black-dark': '#010118',
        'ab-blown-dark': '#531a1d',
        'ab-dark-v1': '#49404B',
        'ab-blown-light': '#F24A25',
        'ab-red-dark': '#FF0000',
        'ab-common-white': '#FFFFFF',
        'ab-common-black': '#000000',
        'ab-orange-v1': '#F48724',

        'ab-dark-plum': '#0e0128',
        'ab-twilight-plum': '#281E24',
        'ab-charcoal-gray': '#474546',
        'ab-royal-indigo': '#523ECA',
        'ab-skyline-blue': '#6573FF',
        'ab-coral-sunset': '#FF7F50',
        'ab-peach-glow': '#FFC495',
        'ab-lavender-mist': '#F0EDFF',
        'ab-moonlight-white': '#FAF9FF',
        'ab-dove-white': '#FAFAF8',
        'ab-dove-gray': '#dadee7',
      },
      textShadow: {
        sm: '0 1px 2px var(--tw-shadow-color)',
        DEFAULT: '0 2px 4px var(--tw-shadow-color)',
        lg: '0 8px 16px var(--tw-shadow-color)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    plugin(function ({ matchUtilities, theme }) {
      matchUtilities(
        {
          'text-shadow': (value) => ({
            textShadow: value,
          }),
        },
        { values: theme('textShadow') },
      );
    }),
  ],
};
